version: '3'
services:

  db:
    image: mongo
    container_name: db
    ports:
     - "4002:27017"
    restart: always

  db-fixture:
    image: db-fixture
    build: ./db-fixture
    container_name: db-fixture
    depends_on:
      - db
    
  service:
    image: service
    build: 
      context: ./service
      dockerfile: Dockerfile-dev
    container_name: service
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./service/src:/usr/src/app/src:z
    ports:
     - "4001:80"
    environment:
     - PORT=80
     - DBHOST=mongodb://db:27017
     - NODE_ENV=development
    depends_on:
     - db
    restart: always

  web:
    image: web
    build: 
      context: ./web
      dockerfile: Dockerfile-dev
    container_name: web
    volumes:
     - ./tmp/npm:/root/.npm:z
     - ./web/src:/usr/src/app/src:z
    ports:
     - "4000:80"
    environment:
     - PORT=80
     - NODE_ENV=development
    depends_on:
     - service
    restart: always

